config/routes.rb
Rails.application.routes.draw do

  root 'employees#index'
  devise_for :users
  resources :departaments
  resources :employees

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departament.rb
class Departament < ApplicationRecord
  has_many :employees, :dependent => :destroy
  validates_presence_of :name

  def self.search(query_value)
    if query_value.present?
      Departament.where(["lower(name) LIKE ?", "#{query_value.downcase}%"])
    else
      Departament.all
    end
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :departament
  validates :name,  presence: true, length: { minimum: 4 }

  def self.search(query_value)
    if query_value.present?
      Employee.where(["lower(name) LIKE ?", "#{query_value.downcase}%"])
    else
      Employee.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :set_departament, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @departament = Departament.new
  end

  def index
    @departaments  = Departament.search(params[:search]).paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def edit
  end

  def create
    @departament = Departament.new(departament_params)
    if @departament.save
    redirect_to @departament, success: "Departament successfully create"
    else
      render 'new', danger: "Departament not updated"
    end
  end

  def update
    if @departament.update(departament_params)
      redirect_to @departament, success: "Departament successfully update"
    else
      render 'edit', danger: "Departament not updated"
    end
  end

  def destroy
    @departament.destroy
    redirect_to departaments_path, danger: "Departament successfully delete"
  end

  private

    def departament_params
      params.require(:departament).permit(:name)
    end

    def set_departament
      @departament = Departament.find(params[:id])
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def new
    @employee = Employee.new
  end

  def index
    @employees  = Employee.search(params[:search]).includes(:departament).paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
    redirect_to @employee, success: "Employee successfully create"
    else
      render 'new', danger: "Employee not updated"
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, success: "Employee successfully update"
    else
      render 'edit', danger: "Employee not updated"
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, danger: "Employee successfully delete"
  end

  private

    def employee_params
      params.require(:employee).permit(:name, :active, :departament_id)
    end

    def set_employee
      @employee = Employee.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def departament_select
    Departament.all.pluck(:name, :id)
  end
end

app/views/departaments/_departament_table.html.slim
= form_for 'departaments', method: :get  do |f|
  = label_tag 'search'
  = text_field_tag 'search', '', class: 'form-control'
  = f.submit 'Search', class: 'btn btn-success mt-1'
br

app/views/departaments/_each_departament.html.slim
- @departaments.each do |departament|
  tr
    td= departament.id
    td= departament.name
    td
      = link_to 'Show', departament_path(departament), class: 'btn btn-success'
      = link_to 'Edit', edit_departament_path(departament), class: 'btn btn-primary'
      = link_to 'Destroy', departament_path(departament),            \
        method: :delete,                                             \
        data: { confirm: 'Are you sure?' } , class: 'btn btn-danger'

app/views/departaments/_form.html.slim
= simple_form_for(@departament, html: { class: 'form-group' }) do |f|
  = f.input :name, placeholder: 'name', error: 'name is mandatory, please specify one'
  = f.button :submit, class: 'btn btn-success'

app/views/departaments/edit.html.slim
h1 Editing Departament
= render 'form'
= link_to 'Back', departaments_path, class: 'btn btn-success'

app/views/departaments/index.html.slim
.container
  h1 Departaments
  br/
  = link_to 'New Departament',  new_departament_path, class: 'btn btn-success'
  br/
  br/
  = render 'departament_table'
  table.table.table-hover.table-dark
    tr
      th Id
      th Name
      th Actions
    = render 'each_departament', collection: @departaments;
  = will_paginate @departaments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/departaments/new.html.slim
h1 New Departament
= render 'form'
= link_to 'Back', departaments_path, class: 'btn btn-success'

app/views/departaments/show.html.slim
p
  strong Name:
  = @departament.name
= link_to 'Edit', edit_departament_path(@departament), class: 'btn btn-success mx-1'
= link_to 'Back', departaments_path, class: 'btn btn-success mx-1'
= link_to 'Destroy', departament_path(@departament),
  method: :delete,
  data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/employees/_each_employee.html.slim
- @employees.each do |employee|
  tr
    td= employee.id
    td= employee.name
    td= employee.active
    td= employee.departament.name
    td
      = link_to 'Show', employee_path(employee), class: 'btn btn-success'
      = link_to 'Edit', edit_employee_path(employee), class: 'btn btn-primary'
      = link_to 'Destroy', employee_path(employee),

        method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/employees/_employee_table.html.slim
= form_for 'employees', method: :get  do |f|
  = label_tag 'search'
  = text_field_tag 'search', '', class: 'form-control'
  = f.submit 'Search', class: 'btn btn-success mt-1'
br

app/views/employees/_form.html.slim
= simple_form_for(@employee, html: { class: 'form-group' }) do |f|
  = f.input :name, label: 'name', error: 'name is mandatory, please specify one and minimum: 4',  input_html: { maxlength: 20 },required: true
  = f.select :departament_id, departament_select
  = f.input :active, inline_label: 'Active'
  = f.button :submit, class: 'btn btn-success'

app/views/employees/edit.html.slim
h1 Editing Employee
= render 'form'
= link_to 'Back',  employees_path, class: 'btn btn-success'

app/views/employees/index.html.slim
.container
  h1 Employees
  br/
  = link_to 'New Employee',  new_employee_path, class: 'btn btn-success'
  br/
  br/
  = render 'employee_table'
  table.table.table-hover.table-dark
    tr
      th Id
      th Name
      th Active
      th Departament
      th Actions
    = render 'each_employee', collection: @employees;
  = will_paginate @employees, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/employees/new.html.slim
h1 New Employee
= render 'form'
= link_to 'Back',  employees_path, class: 'btn btn-success'

app/views/employees/show.html.slim
p
  strong Name:
  = @employee.name
= link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-success mx-1'
= link_to 'Back', employees_path, class: 'btn btn-success mx-1'
= link_to 'Destroy', employee_path(@employee),
  method: :delete,
  data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mx-1'

app/views/layouts/_flash_messages.html.slim
- flash.each do |name, message|
  div class=("alert alert-#{name}")
    button.close data-dismiss="alert" type="button"  ×
    = message

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  h1.logo href="/"  Company
  button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
    ul.nav.navbar-nav.navigation
           - if user_signed_in?
             li.nav-item.us
              li = link_to 'All Departaments', departaments_path
              li = link_to 'All Employees',  employees_path
              li = link_to('Logout', destroy_user_session_path, method: :delete)
              li = link_to current_user.email, edit_user_registration_path
           - else
             li.nav-item.us
              li = link_to('Login', new_user_session_path)
              li = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Company</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar'%>
    <div class='row'>
      <div class='col-md-12'>
        <%= render partial: 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>